name: Scorecard CLI
on:
  # Only the default branch is supported.
  branch_protection_rule:
  #schedule:
  #  - cron: '30 1 * * 0'
  # push:
  #   branches: [ "main" ]
  # pull_request:
    # The branches below must be a subset of the branches above
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      repo:
        type: choice
        description: Public repo to analyze
        options: 
        - npm/cli
        - vuejs/vue
        - facebook/react
        - tensorflow/tensorflow
        - TheAlgorithms/Python

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Used to receive a badge. (Upcoming feature)
      id-token: write
      # Needs for private repositories.
      contents: read
      actions: read
    
    steps:
      # Verify go version
      - name: Verify go version
        id: go
        run: echo $ go version
        
      # Run scorecard with homebrew
      - name: Run scorecard with homebrew
        id: brew
        run: |
          export GITHUB_AUTH_TOKEN=${{ secrets.SCORECARD_READ_TOKEN }}
          brew install scorecard
          scorecard --repo=${{ inputs.repo }} | tee -a output.txt

      # Remove forward slash (/) from repo name for results file name
      - name: Replace forward slash
        id: repo_path
        run: |
          REPO=${{ inputs.repo }}
          REPO_PATH="${REPO//\//-}"
          echo "repo_path=$REPO_PATH" >> $GITHUB_ENV
          
        # echo "::set-output name=repo_path::$REPO_PATH"

      # Get current date
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        

      # Upload the results as artifacts (optional). Commenting out will disable uploads of run results in SARIF
      # format to the repository Actions tab.
      - name: "Upload artifact"
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v3.0.0
        with:
          name: "${{ env.repo_path }}_${{ env.date }}_scorecard-output"
          path: output.txt
          retention-days: 5
      
